// Generates supabase/seed.sql from src/lib/seed-data.ts (single source of truth).
// Usage: node scripts/generate-seed.mts   (Node 23.6+ strips TypeScript types natively)
import { writeFileSync } from "node:fs";
import { SEED_POSTS, SEED_TESTIMONIALS } from "../src/lib/seed-data.ts";

const q = (v: string | number | boolean | null): string =>
  v === null ? "NULL" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);

const posts = SEED_POSTS.map(
  (p) =>
    `(${[p.id, p.title, p.slug, p.excerpt, p.content, p.cover_image_url, p.published_at, p.category, p.author, p.read_time, p.meta_description, p.is_published]
      .map(q)
      .join(", ")})`,
).join(",\n");

const testimonials = SEED_TESTIMONIALS.map(
  (t) => `(${[t.id, t.carrier_name, t.truck_type, t.rating, t.review_text, t.location, t.is_featured, t.created_at].map(q).join(", ")})`,
).join(",\n");

const sql = `-- AUTO-GENERATED by scripts/generate-seed.mts — do not edit by hand.
-- Seed data for Apex Truckin: 3 blog posts + 5 testimonials. Safe to re-run.

INSERT INTO posts (id, title, slug, excerpt, content, cover_image_url, published_at, category, author, read_time, meta_description, is_published)
VALUES
${posts}
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, excerpt = EXCLUDED.excerpt, content = EXCLUDED.content,
  cover_image_url = EXCLUDED.cover_image_url, category = EXCLUDED.category, author = EXCLUDED.author,
  read_time = EXCLUDED.read_time, meta_description = EXCLUDED.meta_description;

INSERT INTO testimonials (id, carrier_name, truck_type, rating, review_text, location, is_featured, created_at)
VALUES
${testimonials}
ON CONFLICT (id) DO NOTHING;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(`✔ supabase/seed.sql — ${SEED_POSTS.length} posts, ${SEED_TESTIMONIALS.length} testimonials`);
