/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    flightHero: FlightHeroBlock;
    howItWorks: HowItWorksBlock;
    coverageMap: CoverageMapBlock;
    pageHero: PageHeroBlock;
    marquee: MarqueeBlock;
    stats: StatsBlock;
    fullService: FullServiceBlock;
    steps: StepsBlock;
    servicesTabs: ServicesTabsBlock;
    servicesGrid: ServicesGridBlock;
    servicesCompare: ServicesCompareBlock;
    pricing: PricingBlock;
    pricingCompare: PricingCompareBlock;
    testimonials: TestimonialsBlock;
    faq: FaqBlock;
    blogPreview: BlogPreviewBlock;
    ctaBanner: CtaBannerBlock;
    contact: ContactBlock;
    team: TeamBlock;
    timeline: TimelineBlock;
    values: ValuesBlock;
    requirements: RequirementsBlock;
    richText: RichTextBlock;
    imageText: ImageTextBlock;
  };
  collections: {
    leads: Lead;
    subscribers: Subscriber;
    services: Service;
    'pricing-tiers': PricingTier;
    testimonials: Testimonial;
    faqs: Faq;
    team: Team;
    posts: Post;
    categories: Category;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'pricing-tiers': PricingTiersSelect<false> | PricingTiersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-content': SiteContent;
    'home-page': HomePage;
    notifications: Notification;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlightHeroBlock".
 */
export interface FlightHeroBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Each beat is a screenful of the scroll-scrubbed hero. The first beat is the intro screen (brand name, live-dot pill, 2 buttons); the rest are supporting screens.
   */
  beats?:
    | {
        /**
         * Short word shown on the scroll progress rail, e.g. Apex, 24/7.
         */
        railLabel: string;
        /**
         * First beat: text next to the live dot. Others: small amber kicker above the heading.
         */
        eyebrow?: string | null;
        heading: string;
        /**
         * Words shown in the orange gradient right after the heading.
         */
        highlight?: string | null;
        /**
         * Optional plain words after the highlighted ones.
         */
        tail?: string | null;
        subheading?: string | null;
        /**
         * {{subTagline}}, {{name}} etc. are replaced with your Site settings values.
         */
        body?: string | null;
        chips?:
          | {
              icon?:
                | (
                    | 'phone-call'
                    | 'search'
                    | 'handshake'
                    | 'truck'
                    | 'file-check'
                    | 'map-pinned'
                    | 'dollar-sign'
                    | 'clipboard-check'
                    | 'clock-3'
                    | 'route'
                    | 'network'
                    | 'shield-check'
                  )
                | null;
              text: string;
              id?: string | null;
            }[]
          | null;
        ctas?:
          | {
              label: string;
              href: string;
              variant?: ('primary' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'flightHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock".
 */
export interface HowItWorksBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'howItWorks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverageMapBlock".
 */
export interface CoverageMapBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  regions?:
    | {
        name: string;
        states?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coverageMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  eyebrow: string;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  /**
   * {{city}}, {{founded}} etc. are replaced with your Site settings values.
   */
  subtitle?: string | null;
  /**
   * Leave empty for a plain dark background.
   */
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * A page path like /contact, or a full https:// URL.
     */
    href?: string | null;
  };
  size?: ('default' | 'short' | 'legal') | null;
  updated?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required.
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock".
 */
export interface MarqueeBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  reverse?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullServiceBlock".
 */
export interface FullServiceBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * A page path like /contact, or a full https:// URL.
     */
    href?: string | null;
  };
  /**
   * Split style only — background photo.
   */
  image?: (number | null) | Media;
  style?: ('split' | 'cards' | 'compact') | null;
  showStats?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullService';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  style?: ('list' | 'grid') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesTabsBlock".
 */
export interface ServicesTabsBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesCompareBlock".
 */
export interface ServicesCompareBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  emitCollectionLd?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesCompare';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  /**
   * Leave empty to show just the plan cards with no heading.
   */
  heading?: string | null;
  highlight?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCompareBlock".
 */
export interface PricingCompareBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingCompare';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading?: string | null;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  source?: ('group' | 'picked') | null;
  group?: ('general' | 'pricing' | 'service') | null;
  items?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * Shared FAQs. Service-specific FAQs live on each service instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * In the service-page group, {service} is replaced with the service name (e.g. dry van).
   */
  question: string;
  /**
   * Plain text. It is also published to Google as FAQ structured data.
   */
  answer: string;
  group: 'general' | 'pricing' | 'service';
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPreviewBlock".
 */
export interface BlogPreviewBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  cta?: {
    label?: string | null;
    /**
     * A page path like /contact, or a full https:// URL.
     */
    href?: string | null;
  };
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  body?: string | null;
  truck?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading?: string | null;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  formHeading?: string | null;
  /**
   * Section style only, e.g. "Dispatch desk online now".
   */
  statusLine?: string | null;
  /**
   * Section style only, e.g. "Avg. reply < 1 hr".
   */
  replyNote?: string | null;
  style?: ('section' | 'page') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        year: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock".
 */
export interface ValuesBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  /**
   * Background photo.
   */
  image?: (number | null) | Media;
  cards?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'values';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RequirementsBlock".
 */
export interface RequirementsBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  intro?: string | null;
  cta?: {
    label?: string | null;
    /**
     * A page path like /contact, or a full https:// URL.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'requirements';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  width?: ('820' | '1100') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  /**
   * Untick to hide this section without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Small pill above the heading, e.g. "What we do".
   */
  label?: string | null;
  numbering?: ('counter' | 'dash' | 'none') | null;
  heading: string;
  /**
   * Words shown in the orange gradient right after the heading.
   */
  highlight?: string | null;
  /**
   * Optional plain words after the highlighted ones.
   */
  tail?: string | null;
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * A page path like /contact, or a full https:// URL.
     */
    href?: string | null;
  };
  image: number | Media;
  imageSide?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * Every contact-form submission lands here. Work it through the pipeline with Status, Follow-up date and Notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  fullName: string;
  status: 'new' | 'contacted' | 'qualified' | 'onboarded' | 'lost';
  followUpAt?: string | null;
  email: string;
  phone?: string | null;
  equipmentType?: string | null;
  message?: string | null;
  mcNumber?: string | null;
  dotNumber?: string | null;
  truckCount?: number | null;
  /**
   * Call notes, next steps — newest at the bottom.
   */
  notes?:
    | {
        text: string;
        createdAt?: string | null;
        author?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  source?: ('home' | 'contact' | 'service' | 'other' | 'manual') | null;
  sourcePath?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  status: 'active' | 'unsubscribed';
  /**
   * Page the visitor subscribed from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Equipment types you dispatch. Each gets its own page at /services/<slug>, a tab on the home page, a footer link, and a column in the comparison table.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. Dry Van. The word Dispatch is added automatically where needed.
   */
  name: string;
  /**
   * One line for cards and lists.
   */
  short: string;
  tagline: string;
  description: string;
  image: number | Media;
  /**
   * e.g. $2.00 – $3.00 / mile
   */
  avgRate: string;
  /**
   * e.g. $7,500 – $8,500. Estimate at ~2,500–3,000 mi/week — shown with the rate disclaimers from Site settings.
   */
  weeklyGross: string;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  typicalLoads?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  comparison?: {
    cdl?: ('yes' | 'no' | 'depends') | null;
    tarpPay?: boolean | null;
    permits?: boolean | null;
    tempMonitoring?: boolean | null;
    dropHook?: boolean | null;
  };
  /**
   * Defaults to the page's standard title.
   */
  metaTitle?: string | null;
  /**
   * Defaults to the description.
   */
  metaDescription?: string | null;
  /**
   * The URL part, e.g. dry-van-vs-flatbed. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers".
 */
export interface PricingTier {
  id: number;
  name: string;
  /**
   * e.g. 5%, $300, Custom
   */
  price: string;
  /**
   * e.g. per truck / month
   */
  unit: string;
  blurb: string;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta: string;
  /**
   * Highlights the plan (Most popular).
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  carrierName: string;
  reviewText: string;
  rating: number;
  truckType?: string | null;
  location?: string | null;
  /**
   * Featured reviews show first.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  photo: number | Media;
  bio: string;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences shown on blog cards and above the article.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The URL part, e.g. dry-van-vs-flatbed. Leave empty to generate it from the title.
   */
  slug: string;
  category: number | Category;
  cover?: (number | null) | Media;
  author?: string | null;
  /**
   * Set automatically on first publish if empty.
   */
  publishedAt?: string | null;
  /**
   * Calculated from the article length.
   */
  readTime?: number | null;
  /**
   * Defaults to the post title.
   */
  metaTitle?: string | null;
  /**
   * ~150 characters for search results. Defaults to the excerpt.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * The URL part, e.g. dry-van-vs-flatbed. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers show first in the blog filter.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Build any page from reorderable sections. About, Carriers, Pricing, Contact, Services, Privacy and Terms are all built this way.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Short name used in breadcrumbs and the sitemap, e.g. "About". The browser/Google title is set separately under SEO.
   */
  title: string;
  /**
   * The URL part, e.g. dry-van-vs-flatbed. Leave empty to generate it from the title.
   */
  slug: string;
  layout: (
    | PageHeroBlock
    | MarqueeBlock
    | StatsBlock
    | FullServiceBlock
    | StepsBlock
    | ServicesTabsBlock
    | ServicesGridBlock
    | ServicesCompareBlock
    | PricingBlock
    | PricingCompareBlock
    | TestimonialsBlock
    | FaqBlock
    | BlogPreviewBlock
    | CtaBannerBlock
    | ContactBlock
    | TeamBlock
    | TimelineBlock
    | ValuesBlock
    | RequirementsBlock
    | RichTextBlock
    | ImageTextBlock
  )[];
  /**
   * Defaults are derived from the page content when left empty.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Rarely needed — leave empty unless this page duplicates another URL.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  showInSitemap?: boolean | null;
  changeFrequency?: ('weekly' | 'monthly' | 'yearly') | null;
  sitemapPriority?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pricing-tiers';
        value: number | PricingTier;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  status?: T;
  followUpAt?: T;
  email?: T;
  phone?: T;
  equipmentType?: T;
  message?: T;
  mcNumber?: T;
  dotNumber?: T;
  truckCount?: T;
  notes?:
    | T
    | {
        text?: T;
        createdAt?: T;
        author?: T;
        id?: T;
      };
  source?: T;
  sourcePath?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  short?: T;
  tagline?: T;
  description?: T;
  image?: T;
  avgRate?: T;
  weeklyGross?: T;
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  typicalLoads?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  comparison?:
    | T
    | {
        cdl?: T;
        tarpPay?: T;
        permits?: T;
        tempMonitoring?: T;
        dropHook?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers_select".
 */
export interface PricingTiersSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  unit?: T;
  blurb?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  carrierName?: T;
  reviewText?: T;
  rating?: T;
  truckType?: T;
  location?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  slug?: T;
  category?: T;
  cover?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageHero?: T | PageHeroBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        fullService?: T | FullServiceBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        servicesTabs?: T | ServicesTabsBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        servicesCompare?: T | ServicesCompareBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        pricingCompare?: T | PricingCompareBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        blogPreview?: T | BlogPreviewBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        values?: T | ValuesBlockSelect<T>;
        requirements?: T | RequirementsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  showInSitemap?: T;
  changeFrequency?: T;
  sitemapPriority?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  subtitle?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  size?: T;
  updated?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock_select".
 */
export interface MarqueeBlockSelect<T extends boolean = true> {
  enabled?: T;
  reverse?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullServiceBlock_select".
 */
export interface FullServiceBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  style?: T;
  showStats?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesTabsBlock_select".
 */
export interface ServicesTabsBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  enabled?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesCompareBlock_select".
 */
export interface ServicesCompareBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  emitCollectionLd?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCompareBlock_select".
 */
export interface PricingCompareBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  source?: T;
  group?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPreviewBlock_select".
 */
export interface BlogPreviewBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  enabled?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  body?: T;
  truck?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  formHeading?: T;
  statusLine?: T;
  replyNote?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock_select".
 */
export interface ValuesBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  image?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RequirementsBlock_select".
 */
export interface RequirementsBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  enabled?: T;
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  imageSide?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company details, navigation and footer — used on every page and in Google structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName: string;
  founded?: number | null;
  tagline: string;
  subTagline: string;
  phone: string;
  /**
   * Digits with country code, e.g. +18880000000. Used for tap-to-call links.
   */
  phoneE164: string;
  email: string;
  /**
   * Digits only, with country code.
   */
  whatsappNumber: string;
  /**
   * Pre-filled message when a visitor taps WhatsApp.
   */
  whatsappMessage?: string | null;
  address: {
    street: string;
    city: string;
    region: string;
    postal: string;
    country: string;
  };
  hours?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    x?: string | null;
  };
  /**
   * Publishes round-the-clock opening hours in Google's structured data. Turn off if the dispatch desk has set hours.
   */
  open24x7?: boolean | null;
  rateDisclaimer: string;
  grossDisclaimer: string;
  /**
   * Rendered in <head> — e.g. a Google Analytics (GA4) or Google Tag Manager snippet, a Meta Pixel base code, or extra <meta>/<link> tags.
   */
  headHtml?: string | null;
  /**
   * Rendered just before </body> — e.g. Google Tag Manager's <noscript> snippet, or a chat-widget script.
   */
  bodyEndHtml?: string | null;
  /**
   * One https:// origin per line. Only needed if a script above loads something from a domain not already covered automatically — e.g. a Tag Manager container that loads a vendor tag at runtime. The browser console will say "Refused to load/connect" and name the blocked domain.
   */
  extraAllowedDomains?: string | null;
  /**
   * The content value only, not the full <meta> tag.
   */
  googleSiteVerification?: string | null;
  /**
   * The content value only, not the full <meta> tag.
   */
  bingSiteVerification?: string | null;
  /**
   * Top navigation and mobile menu (also the footer Company column).
   */
  nav?:
    | {
        label: string;
        /**
         * A page path like /pricing
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerHeadline: string;
  /**
   * Shown after the headline in the orange gradient.
   */
  footerHighlight?: string | null;
  /**
   * Shown faintly behind the footer. Leave empty for the default sunset photo.
   */
  footerImage?: (number | null) | Media;
  newsletterLabel?: string | null;
  footerBottomLine?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Lists reused across several pages — steps, stats, the full-service items, marquee items, carrier requirements and the pricing comparison table.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  marqueeItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: number;
        decimals?: number | null;
        /**
         * e.g. +, " States", ★, /7
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  fullService?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        title: string;
        icon?:
          | (
              | 'phone-call'
              | 'search'
              | 'handshake'
              | 'truck'
              | 'file-check'
              | 'map-pinned'
              | 'dollar-sign'
              | 'clipboard-check'
              | 'clock-3'
              | 'route'
              | 'network'
              | 'shield-check'
            )
          | null;
        body: string;
        id?: string | null;
      }[]
    | null;
  carrierRequirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Each row is a feature; each cell says whether a plan includes it (or a short replacement label, e.g. "Up to 2").
   */
  pricingComparison?:
    | {
        feature: string;
        cells?:
          | {
              tier: number | PricingTier;
              included?: boolean | null;
              /**
               * Optional — replaces the check/dash.
               */
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The sections that make up the home page, in order. Drag to reorder, untick to hide, or add a new section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  layout: (
    | FlightHeroBlock
    | HowItWorksBlock
    | CoverageMapBlock
    | PageHeroBlock
    | MarqueeBlock
    | StatsBlock
    | FullServiceBlock
    | StepsBlock
    | ServicesTabsBlock
    | ServicesGridBlock
    | ServicesCompareBlock
    | PricingBlock
    | PricingCompareBlock
    | TestimonialsBlock
    | FaqBlock
    | BlogPreviewBlock
    | CtaBannerBlock
    | ContactBlock
    | TeamBlock
    | TimelineBlock
    | ValuesBlock
    | RequirementsBlock
    | RichTextBlock
    | ImageTextBlock
  )[];
  /**
   * Defaults are derived from the page content when left empty.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Rarely needed — leave empty unless this page duplicates another URL.
     */
    canonical?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Who gets emailed about new leads, and the automatic reply carriers receive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Everyone listed gets an email the moment a contact form is submitted.
   */
  leadAlertRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  autoReply?: {
    enabled?: boolean | null;
    subject?: string | null;
    /**
     * Plain text. {{name}} is replaced with the carrier's first name.
     */
    body?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  founded?: T;
  tagline?: T;
  subTagline?: T;
  phone?: T;
  phoneE164?: T;
  email?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postal?: T;
        country?: T;
      };
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        x?: T;
      };
  open24x7?: T;
  rateDisclaimer?: T;
  grossDisclaimer?: T;
  headHtml?: T;
  bodyEndHtml?: T;
  extraAllowedDomains?: T;
  googleSiteVerification?: T;
  bingSiteVerification?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerHeadline?: T;
  footerHighlight?: T;
  footerImage?: T;
  newsletterLabel?: T;
  footerBottomLine?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        decimals?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  fullService?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        icon?: T;
        body?: T;
        id?: T;
      };
  carrierRequirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pricingComparison?:
    | T
    | {
        feature?: T;
        cells?:
          | T
          | {
              tier?: T;
              included?: T;
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        flightHero?: T | FlightHeroBlockSelect<T>;
        howItWorks?: T | HowItWorksBlockSelect<T>;
        coverageMap?: T | CoverageMapBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        fullService?: T | FullServiceBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        servicesTabs?: T | ServicesTabsBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        servicesCompare?: T | ServicesCompareBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        pricingCompare?: T | PricingCompareBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        blogPreview?: T | BlogPreviewBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        values?: T | ValuesBlockSelect<T>;
        requirements?: T | RequirementsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlightHeroBlock_select".
 */
export interface FlightHeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  beats?:
    | T
    | {
        railLabel?: T;
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        tail?: T;
        subheading?: T;
        body?: T;
        chips?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock_select".
 */
export interface HowItWorksBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoverageMapBlock_select".
 */
export interface CoverageMapBlockSelect<T extends boolean = true> {
  enabled?: T;
  label?: T;
  numbering?: T;
  heading?: T;
  highlight?: T;
  tail?: T;
  intro?: T;
  regions?:
    | T
    | {
        name?: T;
        states?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  leadAlertRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  autoReply?:
    | T
    | {
        enabled?: T;
        subject?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: 'home-page' | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}